### PR TITLE
[common] String to date conversion to return with GError when null string. Fixes MER#1178

### PR DESCRIPTION
**Pull request by tanty**

### CODE REVIEW

**Comment by foolab** [comment]
Shouldn't we wait until upstream accepts this patch?

**Comment by tanty** [comment]
Yeah, let's wait for upstream. In the end, this is not really fixing anything but just ugly logs.

**Comment by tanty** [comment]
This is now committed upstream too.

Please, merge and tag!

**Comment by sledges** [comment]
LGTM (I got no perms to merge)

**Comment by tanty** [comment]
@iamer could you create a tag for this merge?

**Pull request merged**
